name: Check CHANGELOG.md exists

on: workflow_call

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if CHANGELOG.md exists
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "ERROR"
            exit 1
          fi 
      - name: Check if CHANGELOG.md is updated
        run: |
          git fetch origin
          if git diff --name-only origin/${{ github.base_ref }}..origin/${{ github.head_ref }} | grep -q "^CHANGELOG.md" ; then
            echo "Het is updated"
          else
            echo "Error"
            exit 1
          fi