name: Check CHANGELOG.md exists

on: 
  workflow_call:
    inputs:
      file-name:
        description: "Location of the file to be checked"
        required: true
        default: CHANGELOG.md
        type: string

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Check if ${{ inputs.file-name }} exists
        run: |
          if [ ! -f ${{ inputs.file-name }} ]; then
            echo "ERROR"
            exit 1
          fi 
      - name: Check if ${{ inputs.file-name }} is updated
        run: |
          git fetch origin
          if git diff --name-only origin/${{ github.base_ref }}..origin/${{ github.head_ref }} | grep -q "^${{ inputs.file-name }}" ; then
            echo "Het is updated"
          else
            echo "Error"
            exit 1
          fi